import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Tirth's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="description" content="Tirth Patel's portfolio - Explore my projects, skills, and achievements in a creative file explorer design!" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="Tirth Patel, Web Developer, Portfolio, Projects, Software Developer, Fullstack Developer, Frontend Developer, Backend Developer" />
        <meta name="author" content="Tirth Patel" />
        <meta name="robots" content="index, follow" />
        <meta name="google-site-verification" content="KcRVI8mggXp1CuFxr41IADAEJjnBFHhHNiSk457O-5U" />

        <meta property="og:title" content="Tirth's Portfolio" />
        <meta property="og:description" content="Explore Tirth Patel's creative portfolio styled like a file explorer." />
        <meta property="og:image" content="https://tirth-patel-portfolio.vercel.app/images/previewImage.png" />
        <meta property="og:url" content="https://tirth-patel-portfolio.vercel.app/" />
        <meta property="og:type" content="website" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
